// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AdminCloseStatistics is the `adminCloseStatistics` instruction.
type AdminCloseStatistics struct {

	// [0] = [WRITE] statistics
	//
	// [1] = [WRITE, SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAdminCloseStatisticsInstructionBuilder creates a new `AdminCloseStatistics` instruction builder.
func NewAdminCloseStatisticsInstructionBuilder() *AdminCloseStatistics {
	nd := &AdminCloseStatistics{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetStatisticsAccount sets the "statistics" account.
func (inst *AdminCloseStatistics) SetStatisticsAccount(statistics ag_solanago.PublicKey) *AdminCloseStatistics {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(statistics).WRITE()
	return inst
}

// GetStatisticsAccount gets the "statistics" account.
func (inst *AdminCloseStatistics) GetStatisticsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *AdminCloseStatistics) SetAdminAccount(admin ag_solanago.PublicKey) *AdminCloseStatistics {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).WRITE().SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *AdminCloseStatistics) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst AdminCloseStatistics) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AdminCloseStatistics,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AdminCloseStatistics) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AdminCloseStatistics) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Statistics is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *AdminCloseStatistics) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AdminCloseStatistics")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("statistics", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj AdminCloseStatistics) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *AdminCloseStatistics) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewAdminCloseStatisticsInstruction declares a new AdminCloseStatistics instruction with the provided parameters and accounts.
func NewAdminCloseStatisticsInstruction(
	// Accounts:
	statistics ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *AdminCloseStatistics {
	return NewAdminCloseStatisticsInstructionBuilder().
		SetStatisticsAccount(statistics).
		SetAdminAccount(admin)
}
