// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CreateAiModel is the `createAiModel` instruction.
type CreateAiModel struct {
	Name      *string
	Framework *uint8
	License   *uint8
	Type1     *uint8
	Type2     *uint8
	Tags      *string

	// [0] = [WRITE] aiModel
	//
	// [1] = [WRITE, SIGNER] owner
	//
	// [2] = [WRITE] statisticsOwner
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCreateAiModelInstructionBuilder creates a new `CreateAiModel` instruction builder.
func NewCreateAiModelInstructionBuilder() *CreateAiModel {
	nd := &CreateAiModel{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetName sets the "name" parameter.
func (inst *CreateAiModel) SetName(name string) *CreateAiModel {
	inst.Name = &name
	return inst
}

// SetFramework sets the "framework" parameter.
func (inst *CreateAiModel) SetFramework(framework uint8) *CreateAiModel {
	inst.Framework = &framework
	return inst
}

// SetLicense sets the "license" parameter.
func (inst *CreateAiModel) SetLicense(license uint8) *CreateAiModel {
	inst.License = &license
	return inst
}

// SetType1 sets the "type1" parameter.
func (inst *CreateAiModel) SetType1(type1 uint8) *CreateAiModel {
	inst.Type1 = &type1
	return inst
}

// SetType2 sets the "type2" parameter.
func (inst *CreateAiModel) SetType2(type2 uint8) *CreateAiModel {
	inst.Type2 = &type2
	return inst
}

// SetTags sets the "tags" parameter.
func (inst *CreateAiModel) SetTags(tags string) *CreateAiModel {
	inst.Tags = &tags
	return inst
}

// SetAiModelAccount sets the "aiModel" account.
func (inst *CreateAiModel) SetAiModelAccount(aiModel ag_solanago.PublicKey) *CreateAiModel {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(aiModel).WRITE()
	return inst
}

// GetAiModelAccount gets the "aiModel" account.
func (inst *CreateAiModel) GetAiModelAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOwnerAccount sets the "owner" account.
func (inst *CreateAiModel) SetOwnerAccount(owner ag_solanago.PublicKey) *CreateAiModel {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(owner).WRITE().SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *CreateAiModel) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStatisticsOwnerAccount sets the "statisticsOwner" account.
func (inst *CreateAiModel) SetStatisticsOwnerAccount(statisticsOwner ag_solanago.PublicKey) *CreateAiModel {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(statisticsOwner).WRITE()
	return inst
}

// GetStatisticsOwnerAccount gets the "statisticsOwner" account.
func (inst *CreateAiModel) GetStatisticsOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CreateAiModel) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CreateAiModel {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CreateAiModel) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst CreateAiModel) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CreateAiModel,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CreateAiModel) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CreateAiModel) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Name == nil {
			return errors.New("Name parameter is not set")
		}
		if inst.Framework == nil {
			return errors.New("Framework parameter is not set")
		}
		if inst.License == nil {
			return errors.New("License parameter is not set")
		}
		if inst.Type1 == nil {
			return errors.New("Type1 parameter is not set")
		}
		if inst.Type2 == nil {
			return errors.New("Type2 parameter is not set")
		}
		if inst.Tags == nil {
			return errors.New("Tags parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AiModel is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StatisticsOwner is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *CreateAiModel) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CreateAiModel")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=6]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("     Name", *inst.Name))
						paramsBranch.Child(ag_format.Param("Framework", *inst.Framework))
						paramsBranch.Child(ag_format.Param("  License", *inst.License))
						paramsBranch.Child(ag_format.Param("    Type1", *inst.Type1))
						paramsBranch.Child(ag_format.Param("    Type2", *inst.Type2))
						paramsBranch.Child(ag_format.Param("     Tags", *inst.Tags))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        aiModel", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          owner", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("statisticsOwner", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj CreateAiModel) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Framework` param:
	err = encoder.Encode(obj.Framework)
	if err != nil {
		return err
	}
	// Serialize `License` param:
	err = encoder.Encode(obj.License)
	if err != nil {
		return err
	}
	// Serialize `Type1` param:
	err = encoder.Encode(obj.Type1)
	if err != nil {
		return err
	}
	// Serialize `Type2` param:
	err = encoder.Encode(obj.Type2)
	if err != nil {
		return err
	}
	// Serialize `Tags` param:
	err = encoder.Encode(obj.Tags)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CreateAiModel) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return err
	}
	// Deserialize `Framework`:
	err = decoder.Decode(&obj.Framework)
	if err != nil {
		return err
	}
	// Deserialize `License`:
	err = decoder.Decode(&obj.License)
	if err != nil {
		return err
	}
	// Deserialize `Type1`:
	err = decoder.Decode(&obj.Type1)
	if err != nil {
		return err
	}
	// Deserialize `Type2`:
	err = decoder.Decode(&obj.Type2)
	if err != nil {
		return err
	}
	// Deserialize `Tags`:
	err = decoder.Decode(&obj.Tags)
	if err != nil {
		return err
	}
	return nil
}

// NewCreateAiModelInstruction declares a new CreateAiModel instruction with the provided parameters and accounts.
func NewCreateAiModelInstruction(
	// Parameters:
	name string,
	framework uint8,
	license uint8,
	type1 uint8,
	type2 uint8,
	tags string,
	// Accounts:
	aiModel ag_solanago.PublicKey,
	owner ag_solanago.PublicKey,
	statisticsOwner ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *CreateAiModel {
	return NewCreateAiModelInstructionBuilder().
		SetName(name).
		SetFramework(framework).
		SetLicense(license).
		SetType1(type1).
		SetType2(type2).
		SetTags(tags).
		SetAiModelAccount(aiModel).
		SetOwnerAccount(owner).
		SetStatisticsOwnerAccount(statisticsOwner).
		SetSystemProgramAccount(systemProgram)
}
