// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// MigrateMachineRename is the `migrateMachineRename` instruction.
type MigrateMachineRename struct {

	// [0] = [WRITE] machineBefore
	//
	// [1] = [WRITE] machineAfter
	//
	// [2] = [WRITE, SIGNER] signer
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewMigrateMachineRenameInstructionBuilder creates a new `MigrateMachineRename` instruction builder.
func NewMigrateMachineRenameInstructionBuilder() *MigrateMachineRename {
	nd := &MigrateMachineRename{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetMachineBeforeAccount sets the "machineBefore" account.
func (inst *MigrateMachineRename) SetMachineBeforeAccount(machineBefore ag_solanago.PublicKey) *MigrateMachineRename {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(machineBefore).WRITE()
	return inst
}

// GetMachineBeforeAccount gets the "machineBefore" account.
func (inst *MigrateMachineRename) GetMachineBeforeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMachineAfterAccount sets the "machineAfter" account.
func (inst *MigrateMachineRename) SetMachineAfterAccount(machineAfter ag_solanago.PublicKey) *MigrateMachineRename {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(machineAfter).WRITE()
	return inst
}

// GetMachineAfterAccount gets the "machineAfter" account.
func (inst *MigrateMachineRename) GetMachineAfterAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSignerAccount sets the "signer" account.
func (inst *MigrateMachineRename) SetSignerAccount(signer ag_solanago.PublicKey) *MigrateMachineRename {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *MigrateMachineRename) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *MigrateMachineRename) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *MigrateMachineRename {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *MigrateMachineRename) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst MigrateMachineRename) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_MigrateMachineRename,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst MigrateMachineRename) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *MigrateMachineRename) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.MachineBefore is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MachineAfter is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *MigrateMachineRename) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("MigrateMachineRename")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("machineBefore", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" machineAfter", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       signer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj MigrateMachineRename) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *MigrateMachineRename) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewMigrateMachineRenameInstruction declares a new MigrateMachineRename instruction with the provided parameters and accounts.
func NewMigrateMachineRenameInstruction(
	// Accounts:
	machineBefore ag_solanago.PublicKey,
	machineAfter ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *MigrateMachineRename {
	return NewMigrateMachineRenameInstructionBuilder().
		SetMachineBeforeAccount(machineBefore).
		SetMachineAfterAccount(machineAfter).
		SetSignerAccount(signer).
		SetSystemProgramAccount(systemProgram)
}
