// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RefundOrder is the `refundOrder` instruction.
type RefundOrder struct {

	// [0] = [WRITE] machine
	//
	// [1] = [WRITE] order
	//
	// [2] = [WRITE, SIGNER] buyer
	//
	// [3] = [WRITE] buyerAta
	//
	// [4] = [WRITE] sellerAta
	//
	// [5] = [WRITE] model1OwnerAta
	//
	// [6] = [WRITE] model2OwnerAta
	//
	// [7] = [WRITE] model3OwnerAta
	//
	// [8] = [WRITE] model4OwnerAta
	//
	// [9] = [WRITE] model5OwnerAta
	//
	// [10] = [WRITE] statisticsSeller
	//
	// [11] = [WRITE] statisticsModel1Owner
	//
	// [12] = [WRITE] statisticsModel2Owner
	//
	// [13] = [WRITE] statisticsModel3Owner
	//
	// [14] = [WRITE] statisticsModel4Owner
	//
	// [15] = [WRITE] statisticsModel5Owner
	//
	// [16] = [WRITE] vault
	//
	// [17] = [] mint
	//
	// [18] = [] tokenProgram
	//
	// [19] = [] associatedTokenProgram
	//
	// [20] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRefundOrderInstructionBuilder creates a new `RefundOrder` instruction builder.
func NewRefundOrderInstructionBuilder() *RefundOrder {
	nd := &RefundOrder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 21),
	}
	return nd
}

// SetMachineAccount sets the "machine" account.
func (inst *RefundOrder) SetMachineAccount(machine ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(machine).WRITE()
	return inst
}

// GetMachineAccount gets the "machine" account.
func (inst *RefundOrder) GetMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOrderAccount sets the "order" account.
func (inst *RefundOrder) SetOrderAccount(order ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(order).WRITE()
	return inst
}

// GetOrderAccount gets the "order" account.
func (inst *RefundOrder) GetOrderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetBuyerAccount sets the "buyer" account.
func (inst *RefundOrder) SetBuyerAccount(buyer ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(buyer).WRITE().SIGNER()
	return inst
}

// GetBuyerAccount gets the "buyer" account.
func (inst *RefundOrder) GetBuyerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBuyerAtaAccount sets the "buyerAta" account.
func (inst *RefundOrder) SetBuyerAtaAccount(buyerAta ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(buyerAta).WRITE()
	return inst
}

// GetBuyerAtaAccount gets the "buyerAta" account.
func (inst *RefundOrder) GetBuyerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSellerAtaAccount sets the "sellerAta" account.
func (inst *RefundOrder) SetSellerAtaAccount(sellerAta ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(sellerAta).WRITE()
	return inst
}

// GetSellerAtaAccount gets the "sellerAta" account.
func (inst *RefundOrder) GetSellerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetModel1OwnerAtaAccount sets the "model1OwnerAta" account.
func (inst *RefundOrder) SetModel1OwnerAtaAccount(model1OwnerAta ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(model1OwnerAta).WRITE()
	return inst
}

// GetModel1OwnerAtaAccount gets the "model1OwnerAta" account.
func (inst *RefundOrder) GetModel1OwnerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetModel2OwnerAtaAccount sets the "model2OwnerAta" account.
func (inst *RefundOrder) SetModel2OwnerAtaAccount(model2OwnerAta ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(model2OwnerAta).WRITE()
	return inst
}

// GetModel2OwnerAtaAccount gets the "model2OwnerAta" account.
func (inst *RefundOrder) GetModel2OwnerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetModel3OwnerAtaAccount sets the "model3OwnerAta" account.
func (inst *RefundOrder) SetModel3OwnerAtaAccount(model3OwnerAta ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(model3OwnerAta).WRITE()
	return inst
}

// GetModel3OwnerAtaAccount gets the "model3OwnerAta" account.
func (inst *RefundOrder) GetModel3OwnerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetModel4OwnerAtaAccount sets the "model4OwnerAta" account.
func (inst *RefundOrder) SetModel4OwnerAtaAccount(model4OwnerAta ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(model4OwnerAta).WRITE()
	return inst
}

// GetModel4OwnerAtaAccount gets the "model4OwnerAta" account.
func (inst *RefundOrder) GetModel4OwnerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetModel5OwnerAtaAccount sets the "model5OwnerAta" account.
func (inst *RefundOrder) SetModel5OwnerAtaAccount(model5OwnerAta ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(model5OwnerAta).WRITE()
	return inst
}

// GetModel5OwnerAtaAccount gets the "model5OwnerAta" account.
func (inst *RefundOrder) GetModel5OwnerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetStatisticsSellerAccount sets the "statisticsSeller" account.
func (inst *RefundOrder) SetStatisticsSellerAccount(statisticsSeller ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(statisticsSeller).WRITE()
	return inst
}

// GetStatisticsSellerAccount gets the "statisticsSeller" account.
func (inst *RefundOrder) GetStatisticsSellerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetStatisticsModel1OwnerAccount sets the "statisticsModel1Owner" account.
func (inst *RefundOrder) SetStatisticsModel1OwnerAccount(statisticsModel1Owner ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(statisticsModel1Owner).WRITE()
	return inst
}

// GetStatisticsModel1OwnerAccount gets the "statisticsModel1Owner" account.
func (inst *RefundOrder) GetStatisticsModel1OwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetStatisticsModel2OwnerAccount sets the "statisticsModel2Owner" account.
func (inst *RefundOrder) SetStatisticsModel2OwnerAccount(statisticsModel2Owner ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(statisticsModel2Owner).WRITE()
	return inst
}

// GetStatisticsModel2OwnerAccount gets the "statisticsModel2Owner" account.
func (inst *RefundOrder) GetStatisticsModel2OwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetStatisticsModel3OwnerAccount sets the "statisticsModel3Owner" account.
func (inst *RefundOrder) SetStatisticsModel3OwnerAccount(statisticsModel3Owner ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(statisticsModel3Owner).WRITE()
	return inst
}

// GetStatisticsModel3OwnerAccount gets the "statisticsModel3Owner" account.
func (inst *RefundOrder) GetStatisticsModel3OwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetStatisticsModel4OwnerAccount sets the "statisticsModel4Owner" account.
func (inst *RefundOrder) SetStatisticsModel4OwnerAccount(statisticsModel4Owner ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(statisticsModel4Owner).WRITE()
	return inst
}

// GetStatisticsModel4OwnerAccount gets the "statisticsModel4Owner" account.
func (inst *RefundOrder) GetStatisticsModel4OwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetStatisticsModel5OwnerAccount sets the "statisticsModel5Owner" account.
func (inst *RefundOrder) SetStatisticsModel5OwnerAccount(statisticsModel5Owner ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(statisticsModel5Owner).WRITE()
	return inst
}

// GetStatisticsModel5OwnerAccount gets the "statisticsModel5Owner" account.
func (inst *RefundOrder) GetStatisticsModel5OwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

// SetVaultAccount sets the "vault" account.
func (inst *RefundOrder) SetVaultAccount(vault ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[16] = ag_solanago.Meta(vault).WRITE()
	return inst
}

// GetVaultAccount gets the "vault" account.
func (inst *RefundOrder) GetVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(16)
}

// SetMintAccount sets the "mint" account.
func (inst *RefundOrder) SetMintAccount(mint ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[17] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *RefundOrder) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(17)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *RefundOrder) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[18] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *RefundOrder) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(18)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *RefundOrder) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[19] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *RefundOrder) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(19)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RefundOrder) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RefundOrder {
	inst.AccountMetaSlice[20] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RefundOrder) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(20)
}

func (inst RefundOrder) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RefundOrder,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RefundOrder) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RefundOrder) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Machine is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Order is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Buyer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BuyerAta is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SellerAta is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Model1OwnerAta is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Model2OwnerAta is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Model3OwnerAta is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Model4OwnerAta is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Model5OwnerAta is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.StatisticsSeller is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.StatisticsModel1Owner is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.StatisticsModel2Owner is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.StatisticsModel3Owner is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.StatisticsModel4Owner is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.StatisticsModel5Owner is not set")
		}
		if inst.AccountMetaSlice[16] == nil {
			return errors.New("accounts.Vault is not set")
		}
		if inst.AccountMetaSlice[17] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[18] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[19] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[20] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *RefundOrder) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RefundOrder")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=21]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("               machine", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                 order", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                 buyer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("              buyerAta", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("             sellerAta", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        model1OwnerAta", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("        model2OwnerAta", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        model3OwnerAta", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("        model4OwnerAta", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("        model5OwnerAta", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("      statisticsSeller", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta(" statisticsModel1Owner", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta(" statisticsModel2Owner", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta(" statisticsModel3Owner", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta(" statisticsModel4Owner", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta(" statisticsModel5Owner", inst.AccountMetaSlice.Get(15)))
						accountsBranch.Child(ag_format.Meta("                 vault", inst.AccountMetaSlice.Get(16)))
						accountsBranch.Child(ag_format.Meta("                  mint", inst.AccountMetaSlice.Get(17)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(18)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(19)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(20)))
					})
				})
		})
}

func (obj RefundOrder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RefundOrder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRefundOrderInstruction declares a new RefundOrder instruction with the provided parameters and accounts.
func NewRefundOrderInstruction(
	// Accounts:
	machine ag_solanago.PublicKey,
	order ag_solanago.PublicKey,
	buyer ag_solanago.PublicKey,
	buyerAta ag_solanago.PublicKey,
	sellerAta ag_solanago.PublicKey,
	model1OwnerAta ag_solanago.PublicKey,
	model2OwnerAta ag_solanago.PublicKey,
	model3OwnerAta ag_solanago.PublicKey,
	model4OwnerAta ag_solanago.PublicKey,
	model5OwnerAta ag_solanago.PublicKey,
	statisticsSeller ag_solanago.PublicKey,
	statisticsModel1Owner ag_solanago.PublicKey,
	statisticsModel2Owner ag_solanago.PublicKey,
	statisticsModel3Owner ag_solanago.PublicKey,
	statisticsModel4Owner ag_solanago.PublicKey,
	statisticsModel5Owner ag_solanago.PublicKey,
	vault ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *RefundOrder {
	return NewRefundOrderInstructionBuilder().
		SetMachineAccount(machine).
		SetOrderAccount(order).
		SetBuyerAccount(buyer).
		SetBuyerAtaAccount(buyerAta).
		SetSellerAtaAccount(sellerAta).
		SetModel1OwnerAtaAccount(model1OwnerAta).
		SetModel2OwnerAtaAccount(model2OwnerAta).
		SetModel3OwnerAtaAccount(model3OwnerAta).
		SetModel4OwnerAtaAccount(model4OwnerAta).
		SetModel5OwnerAtaAccount(model5OwnerAta).
		SetStatisticsSellerAccount(statisticsSeller).
		SetStatisticsModel1OwnerAccount(statisticsModel1Owner).
		SetStatisticsModel2OwnerAccount(statisticsModel2Owner).
		SetStatisticsModel3OwnerAccount(statisticsModel3Owner).
		SetStatisticsModel4OwnerAccount(statisticsModel4Owner).
		SetStatisticsModel5OwnerAccount(statisticsModel5Owner).
		SetVaultAccount(vault).
		SetMintAccount(mint).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram)
}
