// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RemoveOrder is the `removeOrder` instruction.
type RemoveOrder struct {

	// [0] = [WRITE] order
	//
	// [1] = [WRITE, SIGNER] buyer
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRemoveOrderInstructionBuilder creates a new `RemoveOrder` instruction builder.
func NewRemoveOrderInstructionBuilder() *RemoveOrder {
	nd := &RemoveOrder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetOrderAccount sets the "order" account.
func (inst *RemoveOrder) SetOrderAccount(order ag_solanago.PublicKey) *RemoveOrder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(order).WRITE()
	return inst
}

// GetOrderAccount gets the "order" account.
func (inst *RemoveOrder) GetOrderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBuyerAccount sets the "buyer" account.
func (inst *RemoveOrder) SetBuyerAccount(buyer ag_solanago.PublicKey) *RemoveOrder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(buyer).WRITE().SIGNER()
	return inst
}

// GetBuyerAccount gets the "buyer" account.
func (inst *RemoveOrder) GetBuyerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst RemoveOrder) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RemoveOrder,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RemoveOrder) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RemoveOrder) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Order is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Buyer is not set")
		}
	}
	return nil
}

func (inst *RemoveOrder) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RemoveOrder")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("order", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("buyer", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj RemoveOrder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RemoveOrder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRemoveOrderInstruction declares a new RemoveOrder instruction with the provided parameters and accounts.
func NewRemoveOrderInstruction(
	// Accounts:
	order ag_solanago.PublicKey,
	buyer ag_solanago.PublicKey) *RemoveOrder {
	return NewRemoveOrderInstructionBuilder().
		SetOrderAccount(order).
		SetBuyerAccount(buyer)
}
