// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RemoveAiModel is the `removeAiModel` instruction.
type RemoveAiModel struct {

	// [0] = [WRITE] aiModel
	//
	// [1] = [WRITE, SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRemoveAiModelInstructionBuilder creates a new `RemoveAiModel` instruction builder.
func NewRemoveAiModelInstructionBuilder() *RemoveAiModel {
	nd := &RemoveAiModel{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetAiModelAccount sets the "aiModel" account.
func (inst *RemoveAiModel) SetAiModelAccount(aiModel ag_solanago.PublicKey) *RemoveAiModel {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(aiModel).WRITE()
	return inst
}

// GetAiModelAccount gets the "aiModel" account.
func (inst *RemoveAiModel) GetAiModelAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOwnerAccount sets the "owner" account.
func (inst *RemoveAiModel) SetOwnerAccount(owner ag_solanago.PublicKey) *RemoveAiModel {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(owner).WRITE().SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *RemoveAiModel) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst RemoveAiModel) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RemoveAiModel,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RemoveAiModel) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RemoveAiModel) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AiModel is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *RemoveAiModel) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RemoveAiModel")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("aiModel", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  owner", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj RemoveAiModel) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RemoveAiModel) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRemoveAiModelInstruction declares a new RemoveAiModel instruction with the provided parameters and accounts.
func NewRemoveAiModelInstruction(
	// Accounts:
	aiModel ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *RemoveAiModel {
	return NewRemoveAiModelInstructionBuilder().
		SetAiModelAccount(aiModel).
		SetOwnerAccount(owner)
}
