// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ReportAiModelDatasetReward is the `reportAiModelDatasetReward` instruction.
type ReportAiModelDatasetReward struct {
	Amount *uint64

	// [0] = [WRITE] statisticsOwner
	//
	// [1] = [WRITE, SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewReportAiModelDatasetRewardInstructionBuilder creates a new `ReportAiModelDatasetReward` instruction builder.
func NewReportAiModelDatasetRewardInstructionBuilder() *ReportAiModelDatasetReward {
	nd := &ReportAiModelDatasetReward{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetAmount sets the "amount" parameter.
func (inst *ReportAiModelDatasetReward) SetAmount(amount uint64) *ReportAiModelDatasetReward {
	inst.Amount = &amount
	return inst
}

// SetStatisticsOwnerAccount sets the "statisticsOwner" account.
func (inst *ReportAiModelDatasetReward) SetStatisticsOwnerAccount(statisticsOwner ag_solanago.PublicKey) *ReportAiModelDatasetReward {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(statisticsOwner).WRITE()
	return inst
}

// GetStatisticsOwnerAccount gets the "statisticsOwner" account.
func (inst *ReportAiModelDatasetReward) GetStatisticsOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *ReportAiModelDatasetReward) SetAdminAccount(admin ag_solanago.PublicKey) *ReportAiModelDatasetReward {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).WRITE().SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *ReportAiModelDatasetReward) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst ReportAiModelDatasetReward) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ReportAiModelDatasetReward,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ReportAiModelDatasetReward) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ReportAiModelDatasetReward) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StatisticsOwner is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *ReportAiModelDatasetReward) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ReportAiModelDatasetReward")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Amount", *inst.Amount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("statisticsOwner", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj ReportAiModelDatasetReward) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ReportAiModelDatasetReward) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

// NewReportAiModelDatasetRewardInstruction declares a new ReportAiModelDatasetReward instruction with the provided parameters and accounts.
func NewReportAiModelDatasetRewardInstruction(
	// Parameters:
	amount uint64,
	// Accounts:
	statisticsOwner ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *ReportAiModelDatasetReward {
	return NewReportAiModelDatasetRewardInstructionBuilder().
		SetAmount(amount).
		SetStatisticsOwnerAccount(statisticsOwner).
		SetAdminAccount(admin)
}
