// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RewardPoolDeposit is the `rewardPoolDeposit` instruction.
type RewardPoolDeposit struct {
	Amount *uint64

	// [0] = [WRITE, SIGNER] signer
	//
	// [1] = [WRITE] signerAta
	//
	// [2] = [WRITE] rewardPool
	//
	// [3] = [] mint
	//
	// [4] = [] tokenProgram
	//
	// [5] = [] associatedTokenProgram
	//
	// [6] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRewardPoolDepositInstructionBuilder creates a new `RewardPoolDeposit` instruction builder.
func NewRewardPoolDepositInstructionBuilder() *RewardPoolDeposit {
	nd := &RewardPoolDeposit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetAmount sets the "amount" parameter.
func (inst *RewardPoolDeposit) SetAmount(amount uint64) *RewardPoolDeposit {
	inst.Amount = &amount
	return inst
}

// SetSignerAccount sets the "signer" account.
func (inst *RewardPoolDeposit) SetSignerAccount(signer ag_solanago.PublicKey) *RewardPoolDeposit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *RewardPoolDeposit) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSignerAtaAccount sets the "signerAta" account.
func (inst *RewardPoolDeposit) SetSignerAtaAccount(signerAta ag_solanago.PublicKey) *RewardPoolDeposit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(signerAta).WRITE()
	return inst
}

// GetSignerAtaAccount gets the "signerAta" account.
func (inst *RewardPoolDeposit) GetSignerAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetRewardPoolAccount sets the "rewardPool" account.
func (inst *RewardPoolDeposit) SetRewardPoolAccount(rewardPool ag_solanago.PublicKey) *RewardPoolDeposit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(rewardPool).WRITE()
	return inst
}

// GetRewardPoolAccount gets the "rewardPool" account.
func (inst *RewardPoolDeposit) GetRewardPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMintAccount sets the "mint" account.
func (inst *RewardPoolDeposit) SetMintAccount(mint ag_solanago.PublicKey) *RewardPoolDeposit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *RewardPoolDeposit) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *RewardPoolDeposit) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *RewardPoolDeposit {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *RewardPoolDeposit) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *RewardPoolDeposit) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *RewardPoolDeposit {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *RewardPoolDeposit) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RewardPoolDeposit) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RewardPoolDeposit {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RewardPoolDeposit) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst RewardPoolDeposit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RewardPoolDeposit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RewardPoolDeposit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RewardPoolDeposit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SignerAta is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.RewardPool is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *RewardPoolDeposit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RewardPoolDeposit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Amount", *inst.Amount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                signer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             signerAta", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            rewardPool", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                  mint", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj RewardPoolDeposit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RewardPoolDeposit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

// NewRewardPoolDepositInstruction declares a new RewardPoolDeposit instruction with the provided parameters and accounts.
func NewRewardPoolDepositInstruction(
	// Parameters:
	amount uint64,
	// Accounts:
	signer ag_solanago.PublicKey,
	signerAta ag_solanago.PublicKey,
	rewardPool ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *RewardPoolDeposit {
	return NewRewardPoolDepositInstructionBuilder().
		SetAmount(amount).
		SetSignerAccount(signer).
		SetSignerAtaAccount(signerAta).
		SetRewardPoolAccount(rewardPool).
		SetMintAccount(mint).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram)
}
