// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package distri_ai

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// StartOrder is the `startOrder` instruction.
type StartOrder struct {

	// [0] = [WRITE] order
	//
	// [1] = [WRITE, SIGNER] seller
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStartOrderInstructionBuilder creates a new `StartOrder` instruction builder.
func NewStartOrderInstructionBuilder() *StartOrder {
	nd := &StartOrder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetOrderAccount sets the "order" account.
func (inst *StartOrder) SetOrderAccount(order ag_solanago.PublicKey) *StartOrder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(order).WRITE()
	return inst
}

// GetOrderAccount gets the "order" account.
func (inst *StartOrder) GetOrderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSellerAccount sets the "seller" account.
func (inst *StartOrder) SetSellerAccount(seller ag_solanago.PublicKey) *StartOrder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(seller).WRITE().SIGNER()
	return inst
}

// GetSellerAccount gets the "seller" account.
func (inst *StartOrder) GetSellerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst StartOrder) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_StartOrder,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst StartOrder) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *StartOrder) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Order is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Seller is not set")
		}
	}
	return nil
}

func (inst *StartOrder) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("StartOrder")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" order", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("seller", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj StartOrder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *StartOrder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewStartOrderInstruction declares a new StartOrder instruction with the provided parameters and accounts.
func NewStartOrderInstruction(
	// Accounts:
	order ag_solanago.PublicKey,
	seller ag_solanago.PublicKey) *StartOrder {
	return NewStartOrderInstructionBuilder().
		SetOrderAccount(order).
		SetSellerAccount(seller)
}
